from PyQt5 import QtCore, QtGui, QtWidgets
'''This is the QuizPage
the below class uses Qwidget to create this window
'''

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(994, 656)
        MainWindow.setStyleSheet("* {\n"
"border:none;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(24,24,36);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu_frame = QtWidgets.QFrame(self.centralwidget)
        self.side_menu_frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.side_menu_frame.setStyleSheet("background-color:rgb(9,5,13);\n"
"color:#fff;")
        self.side_menu_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.side_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu_frame.setObjectName("side_menu_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_menu_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.side_menu = QtWidgets.QFrame(self.side_menu_frame)
        self.side_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu.setObjectName("side_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.side_menu)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.side_menu)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setText("Sustain X")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3 = QtWidgets.QPushButton(self.frame_7)
        self.label_3.setText("")
        self.label_3.setIcon(QtGui.QIcon((QtGui.QPixmap("logored.jpeg"))))
        self.label_3.setIconSize(QtCore.QSize(30,30))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.frame_7, 0, QtCore.Qt.AlignTop)
        self.frame_8 = QtWidgets.QFrame(self.side_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolBox = QtWidgets.QToolBox(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("QToolBox{\n"
"background-color:rgb(24,24,36);\n"
"text-align:left;\n"
"}\n"
"\n"
"QToolBox::tab{\n"
"border-radius:5px;\n"
"background-color:rgb(17,16,26);\n"
"text-align:left;\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 232, 478))
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_10 = QtWidgets.QFrame(self.page)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_10.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/alert-triangle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_6.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/bar-chart-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon1)
        self.pushButton_11.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_6.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_12.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/key.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon2)
        self.pushButton_12.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_6.addWidget(self.pushButton_12)
        self.verticalLayout_5.addWidget(self.frame_10, 0, QtCore.Qt.AlignTop)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/chevron-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page, icon3, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 232, 478))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.page_2.setFont(font)
        self.page_2.setObjectName("page_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_11 = QtWidgets.QFrame(self.page_2)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_13.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/printer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon4)
        self.pushButton_13.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_8.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_14.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/phone-missed.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon5)
        self.pushButton_14.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_8.addWidget(self.pushButton_14)
        self.verticalLayout_7.addWidget(self.frame_11, 0, QtCore.Qt.AlignTop)
        self.toolBox.addItem(self.page_2, icon3, "")
        self.verticalLayout_4.addWidget(self.toolBox)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.side_menu)
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_9.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/external-link.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon6)
        self.pushButton_9.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_11.addWidget(self.pushButton_9, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.verticalLayout_3.addWidget(self.frame_9, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_2.addWidget(self.side_menu)
        self.horizontalLayout.addWidget(self.side_menu_frame)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_body)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Main_body_frame = QtWidgets.QFrame(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_body_frame.sizePolicy().hasHeightForWidth())
        self.Main_body_frame.setSizePolicy(sizePolicy)
        self.Main_body_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Main_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main_body_frame.setObjectName("Main_body_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Main_body_frame)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.header_frame = QtWidgets.QFrame(self.Main_body_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame.sizePolicy().hasHeightForWidth())
        self.header_frame.setSizePolicy(sizePolicy)
        self.header_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.header_frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_8.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/align-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon7)
        self.pushButton_8.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_9.addWidget(self.pushButton_8, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_6, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.header_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color:#fff;\n"
"border-bottom: 3px solid rgb(230,5,64);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon8)
        self.pushButton_6.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.horizontalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.header_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setMaximumSize(QtCore.QSize(50, 30))
        self.pushButton_4.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon9)
        self.pushButton_4.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setMaximumSize(QtCore.QSize(50, 30))
        self.pushButton_5.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/bell.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon10)
        self.pushButton_5.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.horizontalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame_3 = QtWidgets.QFrame(self.header_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/arrow-down-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon11)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_2.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/maximize-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon12)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_3.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon13)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.horizontalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout_9.addWidget(self.header_frame)
        self.verticalLayout.addWidget(self.Main_body_frame)
        self.frame_12 = QtWidgets.QFrame(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 554))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_12.setStyleSheet("background-color:qlineargradient(spread:pad, x1:1, y1:0.159091, x2:0, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(173, 93, 93, 182))")
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_10.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_12)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 685, 4018))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 4000))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_4 = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"color:white;\n"
"background:transparent;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_21.addWidget(self.label_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_17.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_17.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 1, 0, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_15.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_15.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 0, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_16.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_16.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 0, 1, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_18.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_18.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 1, 1, 1, 1)
        self.verticalLayout_21.addLayout(self.gridLayout)
        self.label_15 = QtWidgets.QLabel(self.frame_13)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_21.addWidget(self.label_15)
        self.verticalLayout_22.addLayout(self.verticalLayout_21)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("background:transparent;\n"
"color:white;")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_20.addWidget(self.plainTextEdit)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_24 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_24.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_24.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_24.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_3.addWidget(self.pushButton_24, 0, 0, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_25.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_25.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_25.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_3.addWidget(self.pushButton_25, 0, 1, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_26.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_26.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_26.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_3.addWidget(self.pushButton_26, 1, 1, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_23.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_23.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_23.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_3.addWidget(self.pushButton_23, 1, 0, 1, 1)
        self.verticalLayout_20.addLayout(self.gridLayout_3)
        self.label_14 = QtWidgets.QLabel(self.frame_13)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_20.addWidget(self.label_14)
        self.verticalLayout_22.addLayout(self.verticalLayout_20)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setStyleSheet("background:transparent;\n"
"color:white;")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout_19.addWidget(self.plainTextEdit_2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_28 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_28.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_28.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_28.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_4.addWidget(self.pushButton_28, 0, 0, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_29.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_29.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_29.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_4.addWidget(self.pushButton_29, 0, 1, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_27.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_27.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_27.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_4.addWidget(self.pushButton_27, 1, 0, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_30.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_30.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_30.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_4.addWidget(self.pushButton_30, 1, 1, 1, 1)
        self.verticalLayout_19.addLayout(self.gridLayout_4)
        self.label_13 = QtWidgets.QLabel(self.frame_13)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_19.addWidget(self.label_13)
        self.verticalLayout_22.addLayout(self.verticalLayout_19)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setStyleSheet("background:transparent;\n"
"color:white;")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.verticalLayout_18.addWidget(self.plainTextEdit_3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_31 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_31.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_31.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_31.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_5.addWidget(self.pushButton_31, 1, 0, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_32.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_32.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_32.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout_5.addWidget(self.pushButton_32, 0, 0, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_33.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_33.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_33.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout_5.addWidget(self.pushButton_33, 0, 1, 1, 1)
        self.pushButton_34 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_34.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_34.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_34.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayout_5.addWidget(self.pushButton_34, 1, 1, 1, 1)
        self.verticalLayout_18.addLayout(self.gridLayout_5)
        self.label_12 = QtWidgets.QLabel(self.frame_13)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_18.addWidget(self.label_12)
        self.verticalLayout_22.addLayout(self.verticalLayout_18)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.plainTextEdit_4.setFont(font)
        self.plainTextEdit_4.setStyleSheet("background:transparent;\n"
"color:white;")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.verticalLayout_17.addWidget(self.plainTextEdit_4)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_35 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_35.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_35.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_35.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_35.setObjectName("pushButton_35")
        self.gridLayout_6.addWidget(self.pushButton_35, 1, 0, 1, 1)
        self.pushButton_36 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_36.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_36.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_36.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout_6.addWidget(self.pushButton_36, 0, 0, 1, 1)
        self.pushButton_37 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_37.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_37.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_37.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_37.setObjectName("pushButton_37")
        self.gridLayout_6.addWidget(self.pushButton_37, 0, 1, 1, 1)
        self.pushButton_38 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_38.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_38.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_38.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout_6.addWidget(self.pushButton_38, 1, 1, 1, 1)
        self.verticalLayout_17.addLayout(self.gridLayout_6)
        self.label_11 = QtWidgets.QLabel(self.frame_13)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_17.addWidget(self.label_11)
        self.verticalLayout_22.addLayout(self.verticalLayout_17)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.plainTextEdit_5.setFont(font)
        self.plainTextEdit_5.setStyleSheet("background:transparent;\n"
"color:white;")
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.verticalLayout_16.addWidget(self.plainTextEdit_5)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_39 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_39.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_39.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_39.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_39.setObjectName("pushButton_39")
        self.gridLayout_7.addWidget(self.pushButton_39, 1, 0, 1, 1)
        self.pushButton_40 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_40.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_40.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_40.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_40.setObjectName("pushButton_40")
        self.gridLayout_7.addWidget(self.pushButton_40, 0, 0, 1, 1)
        self.pushButton_41 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_41.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_41.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_41.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_41.setObjectName("pushButton_41")
        self.gridLayout_7.addWidget(self.pushButton_41, 0, 1, 1, 1)
        self.pushButton_42 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_42.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_42.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_42.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_42.setObjectName("pushButton_42")
        self.gridLayout_7.addWidget(self.pushButton_42, 1, 1, 1, 1)
        self.verticalLayout_16.addLayout(self.gridLayout_7)
        self.label_10 = QtWidgets.QLabel(self.frame_13)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_16.addWidget(self.label_10)
        self.verticalLayout_22.addLayout(self.verticalLayout_16)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.plainTextEdit_6.setFont(font)
        self.plainTextEdit_6.setStyleSheet("background:transparent;\n"
"color:white;")
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.verticalLayout_15.addWidget(self.plainTextEdit_6)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButton_43 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_43.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_43.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_43.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_43.setObjectName("pushButton_43")
        self.gridLayout_8.addWidget(self.pushButton_43, 1, 0, 1, 1)
        self.pushButton_44 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_44.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_44.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_44.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_44.setObjectName("pushButton_44")
        self.gridLayout_8.addWidget(self.pushButton_44, 0, 0, 1, 1)
        self.pushButton_45 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_45.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_45.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_45.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_45.setObjectName("pushButton_45")
        self.gridLayout_8.addWidget(self.pushButton_45, 0, 1, 1, 1)
        self.pushButton_46 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_46.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_46.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_46.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_46.setObjectName("pushButton_46")
        self.gridLayout_8.addWidget(self.pushButton_46, 1, 1, 1, 1)
        self.verticalLayout_15.addLayout(self.gridLayout_8)
        self.label_9 = QtWidgets.QLabel(self.frame_13)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_15.addWidget(self.label_9)
        self.verticalLayout_22.addLayout(self.verticalLayout_15)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.plainTextEdit_7.setFont(font)
        self.plainTextEdit_7.setStyleSheet("background:transparent;\n"
"color:white;")
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.verticalLayout_14.addWidget(self.plainTextEdit_7)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_47 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_47.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_47.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_47.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_47.setObjectName("pushButton_47")
        self.gridLayout_9.addWidget(self.pushButton_47, 1, 0, 1, 1)
        self.pushButton_48 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_48.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_48.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_48.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_48.setObjectName("pushButton_48")
        self.gridLayout_9.addWidget(self.pushButton_48, 0, 0, 1, 1)
        self.pushButton_49 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_49.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_49.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_49.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_49.setObjectName("pushButton_49")
        self.gridLayout_9.addWidget(self.pushButton_49, 0, 1, 1, 1)
        self.pushButton_50 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_50.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_50.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_50.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_50.setObjectName("pushButton_50")
        self.gridLayout_9.addWidget(self.pushButton_50, 1, 1, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_9)
        self.label_8 = QtWidgets.QLabel(self.frame_13)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_14.addWidget(self.label_8)
        self.verticalLayout_22.addLayout(self.verticalLayout_14)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.plainTextEdit_8 = QtWidgets.QPlainTextEdit(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.plainTextEdit_8.setFont(font)
        self.plainTextEdit_8.setStyleSheet("background:transparent;\n"
"color:white;")
        self.plainTextEdit_8.setObjectName("plainTextEdit_8")
        self.verticalLayout_13.addWidget(self.plainTextEdit_8)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pushButton_51 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_51.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_51.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_51.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_51.setObjectName("pushButton_51")
        self.gridLayout_10.addWidget(self.pushButton_51, 1, 0, 1, 1)
        self.pushButton_52 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_52.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_52.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_52.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_52.setObjectName("pushButton_52")
        self.gridLayout_10.addWidget(self.pushButton_52, 0, 0, 1, 1)
        self.pushButton_53 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_53.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_53.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_53.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_53.setObjectName("pushButton_53")
        self.gridLayout_10.addWidget(self.pushButton_53, 0, 1, 1, 1)
        self.pushButton_54 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_54.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_54.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_54.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_54.setObjectName("pushButton_54")
        self.gridLayout_10.addWidget(self.pushButton_54, 1, 1, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_10)
        self.label_7 = QtWidgets.QLabel(self.frame_13)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_13.addWidget(self.label_7)
        self.verticalLayout_22.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.plainTextEdit_9 = QtWidgets.QPlainTextEdit(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.plainTextEdit_9.setFont(font)
        self.plainTextEdit_9.setStyleSheet("background:transparent;\n"
"color:white;")
        self.plainTextEdit_9.setObjectName("plainTextEdit_9")
        self.verticalLayout_12.addWidget(self.plainTextEdit_9)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pushButton_55 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_55.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_55.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_55.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_55.setObjectName("pushButton_55")
        self.gridLayout_11.addWidget(self.pushButton_55, 1, 0, 1, 1)
        self.pushButton_56 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_56.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_56.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_56.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_56.setObjectName("pushButton_56")
        self.gridLayout_11.addWidget(self.pushButton_56, 0, 0, 1, 1)
        self.pushButton_57 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_57.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_57.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_57.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_57.setObjectName("pushButton_57")
        self.gridLayout_11.addWidget(self.pushButton_57, 0, 1, 1, 1)
        self.pushButton_58 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_58.setMinimumSize(QtCore.QSize(200, 50))
        self.pushButton_58.setMaximumSize(QtCore.QSize(200, 50))
        self.pushButton_58.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color:black;\n"
"color:white\n"
"}")
        self.pushButton_58.setObjectName("pushButton_58")
        self.gridLayout_11.addWidget(self.pushButton_58, 1, 1, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_11)
        self.label_6 = QtWidgets.QLabel(self.frame_13)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.verticalLayout_22.addLayout(self.verticalLayout_12)
        self.verticalLayout_11.addWidget(self.frame_13)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_10.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.frame_12)
        self.footer_frame = QtWidgets.QFrame(self.main_body)
        self.footer_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_frame.setObjectName("footer_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footer_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.footer_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#fff;")
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.footer_frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_7.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("icons/box.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon14)
        self.pushButton_7.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_7.addWidget(self.pushButton_7, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.siz_grip = QtWidgets.QFrame(self.footer_frame)
        self.siz_grip.setMinimumSize(QtCore.QSize(10, 10))
        self.siz_grip.setMaximumSize(QtCore.QSize(10, 10))
        self.siz_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.siz_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.siz_grip.setObjectName("siz_grip")
        self.horizontalLayout_3.addWidget(self.siz_grip, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.footer_frame, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.main_body)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "APP NAME"))
        self.pushButton_10.setText(_translate("MainWindow", "ITEM 1"))
        self.pushButton_11.setText(_translate("MainWindow", "ITEM 2"))
        self.pushButton_12.setText(_translate("MainWindow", "ITEM  3"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "DROP MENU 1"))
        self.pushButton_13.setText(_translate("MainWindow", "SUB MENU"))
        self.pushButton_14.setText(_translate("MainWindow", "SUB MENU "))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "DROP MENU 2"))
        self.pushButton_9.setText(_translate("MainWindow", "Exit"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search"))
        self.label_4.setText(_translate("MainWindow", "1.Where was the sustainable development explained for first time?"))
        self.pushButton_17.setText(_translate("MainWindow", "First Earth Sumit report"))
        self.pushButton_15.setText(_translate("MainWindow", "World Development Report"))
        self.pushButton_16.setText(_translate("MainWindow", "brundtland commission report"))
        self.pushButton_18.setText(_translate("MainWindow", "Human development report"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "2.The 2030 Agenda for Sustainable Development aimed to eradicate poverty by 2030. Sadly it is not on course to meet this target, partly due to COVID-19. What is the global poverty rate predicted to be by 2030?"))
        self.pushButton_24.setText(_translate("MainWindow", "3%"))
        self.pushButton_25.setText(_translate("MainWindow", "7%"))
        self.pushButton_26.setText(_translate("MainWindow", "15%"))
        self.pushButton_23.setText(_translate("MainWindow", "10%"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "3.The second key aim of the agenda is to end hunger. What percentage of the world’s population regularly suffers from hunger?"))
        self.pushButton_28.setText(_translate("MainWindow", "1.2%"))
        self.pushButton_29.setText(_translate("MainWindow", "4.55"))
        self.pushButton_27.setText(_translate("MainWindow", "8.9%"))
        self.pushButton_30.setText(_translate("MainWindow", "10%"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "4.Women’s equality and empowerment is one of the 17 SDGs. The gender pay gap stands at 23%. If current trends continue, in what year will the gender pay gap close?"))
        self.pushButton_31.setText(_translate("MainWindow", "2100"))
        self.pushButton_32.setText(_translate("MainWindow", "2030"))
        self.pushButton_33.setText(_translate("MainWindow", "2080"))
        self.pushButton_34.setText(_translate("MainWindow", "2101"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.plainTextEdit_4.setPlainText(_translate("MainWindow", "5.In order to limit global warming to 1.5°C above pre-industrial levels, scientists say global emissions should be cut to 45 per cent below 2010 levels by 2030. How much lower were emissions from developed countries in 2019 than in 2010?"))
        self.pushButton_35.setText(_translate("MainWindow", "10%"))
        self.pushButton_36.setText(_translate("MainWindow", "6.2%"))
        self.pushButton_37.setText(_translate("MainWindow", "18.9%"))
        self.pushButton_38.setText(_translate("MainWindow", "21.9%"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.plainTextEdit_5.setPlainText(_translate("MainWindow", "6.Ensuring access to sustainable energy is a fundamental target of the SDGs. Which is the largest single renewable electricity source today, providing 16% of world electricity?"))
        self.pushButton_39.setText(_translate("MainWindow", "Solar Power"))
        self.pushButton_40.setText(_translate("MainWindow", "Hydro Power"))
        self.pushButton_41.setText(_translate("MainWindow", "Wind Power"))
        self.pushButton_42.setText(_translate("MainWindow", "thermal Power"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.plainTextEdit_6.setPlainText(_translate("MainWindow", "7.Measures to make human consumption and production more sustainable will lessen the destructive impact we are having on our planet. What proportion of the world’s food is currently thrown away or wasted?"))
        self.pushButton_43.setText(_translate("MainWindow", "1/2"))
        self.pushButton_44.setText(_translate("MainWindow", "1/10"))
        self.pushButton_45.setText(_translate("MainWindow", "1/3"))
        self.pushButton_46.setText(_translate("MainWindow", "1/6"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.plainTextEdit_7.setPlainText(_translate("MainWindow", "8.he ‘Life Below Water’ goal lays out desperately-needed measures to protect our oceans. At current rates, by what year will there be more plastic than fish in oceans?"))
        self.pushButton_47.setText(_translate("MainWindow", "2090"))
        self.pushButton_48.setText(_translate("MainWindow", "2030"))
        self.pushButton_49.setText(_translate("MainWindow", "2050"))
        self.pushButton_50.setText(_translate("MainWindow", "2110"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.plainTextEdit_8.setPlainText(_translate("MainWindow", "9.Goal 11 looks at sustainable cities and communities. What percentage of people living in urban areas are exposed to air quality levels which exceed the guidelines set by the World Health Organization?"))
        self.pushButton_51.setText(_translate("MainWindow", "More than 80%"))
        self.pushButton_52.setText(_translate("MainWindow", " Less than 50%"))
        self.pushButton_53.setText(_translate("MainWindow", "More than 60%"))
        self.pushButton_54.setText(_translate("MainWindow", "More than 100%"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.plainTextEdit_9.setPlainText(_translate("MainWindow", "10.Goal 15 looks at life on land, and how to combat the desertification and degradation which leaves land unable to support life systems. What proportion of land on Earth is currently degraded?"))
        self.pushButton_55.setText(_translate("MainWindow", "1/5"))
        self.pushButton_56.setText(_translate("MainWindow", "1/8"))
        self.pushButton_57.setText(_translate("MainWindow", "1/4"))
        self.pushButton_58.setText(_translate("MainWindow", "1/2"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Mordern UI V 7.7.7"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
