# Form implementation generated from reading ui file 'sign_up_page.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(609, 556)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 30, 550, 500))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 30, 280, 430))
        self.label.setStyleSheet("#label {\n"
"background-image:url(bg.jpg);\n"
"border-top-left-radius:50px;\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(270, 30, 240, 430))
        self.label_2.setStyleSheet("background-color:#fff;\n"
"border-bottom-right-radius:50px")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(335, 60, 111, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#000;\n"
"")
        self.label_3.setObjectName("label_3")
        self.invalid = QtWidgets.QLabel(self.widget)
        self.invalid.setGeometry(QtCore.QRect(295,380,190,40))
        font1 = QtGui.QFont()
        font1.setPointSize(11)
        self.invalid.setFont(font1)
        self.invalid.setText('Incorrect Mail or Password')
        self.invalid.setStyleSheet('color:red')
        
        
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(295, 110, 91, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"background-color:#fff;\n"
"color:rgba(103, 103, 103, 240);\n"
"border:none;\n"
"border-bottom:2px solid black;\n"
"padding-bottom:7px\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(295, 155, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"background-color:#fff;\n"
"color:rgba(103, 103, 103, 240);\n"
"border:none;\n"
"border-bottom:2px solid black;\n"
"padding-bottom:7px\n"
"}")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(295, 335, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("\n"
"QPushButton{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0.568, x2:0, y2:0.994318, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(255, 97, 97, 255));\n"
"\n"
"color:#fff;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"#pushButton:hover{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0.568, x2:0, y2:0.994318, stop:0 rgba(0, 0, 2, 255), stop:1 rgba(255, 97, 97, 255));\n"
"}\n"
"\n"
"#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0.568, x2:0, y2:0.994318, stop:0 rgba(0, 0, 2, 255), stop:1 rgba(0, 97, 97, 255));\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(400, 110, 91, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"background-color:#fff;\n"
"color:rgba(103, 103, 103, 240);\n"
"border:none;\n"
"border-bottom:2px solid black;\n"
"padding-bottom:7px\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(295, 200, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"background-color:#fff;\n"
"color:rgba(103, 103, 103, 240);\n"
"border:none;\n"
"border-bottom:2px solid black;\n"
"padding-bottom:7px\n"
"}")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(295, 245, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"background-color:#fff;\n"
"color:rgba(103, 103, 103, 240);\n"
"border:none;\n"
"border-bottom:2px solid black;\n"
"padding-bottom:7px\n"
"}")
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(295, 290, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("QLineEdit{\n"
"background-color:#fff;\n"
"color:rgba(103, 103, 103, 240);\n"
"border:none;\n"
"border-bottom:2px solid black;\n"
"padding-bottom:7px\n"
"}")
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Register"))
        self.lineEdit.setPlaceholderText(_translate("Form", "First Name"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Mail"))
        self.pushButton.setText(_translate("Form", "Register"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Last Name"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Email"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "Password"))
        self.lineEdit_6.setPlaceholderText(_translate("Form", "Confirm Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
